import { describe, expect, it } from "vitest";
import { EXTENSION_CONFIGURATION_VERSION, EXTENSION_LIMITS, SAFE_EXTENSION_PRESETS, evaluateSafeExtension, migrateSafeExtensionConfiguration, validateSafeExtensionConfiguration } from "../packages/core/src/extensions.js";
import type { CityModel } from "../packages/core/src/model.js";

const model: Pick<CityModel, "schemaVersion" | "buildings"> = { schemaVersion: "1.0", buildings: [{ id: "a", repositoryId: "r", moduleId: "m", districtId: "d", name: "a.ts", path: "a.ts", language: "typescript", metrics: { sloc: 100, decisionLoad: 5, maximumComplexity: 8, executableUnitCount: 2 }, risk: "low", semanticGroupId: "risk", position: { x: 0, y: 0, z: 0 }, size: { x: 1, y: 1, z: 1 } }] };
describe("safe declarative extensions", () => {
  it("evaluates the public preset deterministically without changing the city", () => { const result = evaluateSafeExtension(model, SAFE_EXTENSION_PRESETS[0]); expect(result.derivedMetrics.a!["complexity-pressure"]).toBeGreaterThan(0); expect(result.matches["high-pressure"]).toEqual(["a"]); });
  it("migrates the immediately previous data-only version", () => { const legacy = { ...SAFE_EXTENSION_PRESETS[0], version: "codecity.extensions/0" }; expect(migrateSafeExtensionConfiguration(legacy).version).toBe(EXTENSION_CONFIGURATION_VERSION); });
  it("rejects unknown versions and undeclared capability definitions", () => { expect(() => validateSafeExtensionConfiguration({ ...SAFE_EXTENSION_PRESETS[0], version: "codecity.extensions/99" })).toThrow(); expect(() => validateSafeExtensionConfiguration({ ...SAFE_EXTENSION_PRESETS[0], compatibility: { cityModel: "1.x", capabilities: ["layouts"] } })).toThrow(); });
  it("rejects prototype-pollution and executable-looking fields", () => { const polluted = JSON.parse('{"version":"codecity.extensions/1","id":"x","name":"x","compatibility":{"cityModel":"1.x","capabilities":[]},"scope":{"kind":"project"},"__proto__":{"polluted":true}}'); expect(() => validateSafeExtensionConfiguration(polluted)).toThrow(); expect(() => validateSafeExtensionConfiguration({ ...SAFE_EXTENSION_PRESETS[0], script: "process.env.SECRET" })).toThrow(); });
  it("bounds pathological expressions and evaluation operations", () => { let expression: unknown = { op: "constant", value: 1 }; for (let index = 0; index < EXTENSION_LIMITS.expressionDepth + 2; index++) expression = { op: "negate", value: expression }; const candidate = { version: EXTENSION_CONFIGURATION_VERSION, id: "too-deep", name: "Too deep", compatibility: { cityModel: "1.x", capabilities: ["derived-metrics"] }, scope: { kind: "project" }, derivedMetrics: [{ id: "x", label: "x", expression }] }; expect(() => validateSafeExtensionConfiguration(candidate)).toThrow(/expression limits/); expect(() => evaluateSafeExtension(model, SAFE_EXTENSION_PRESETS[0], { checkpoint: () => { throw new DOMException("cancelled", "AbortError"); } })).toThrow(/cancelled/); });
});
