import { describe, expect, it } from "vitest";
import { projectFineDetail } from "../apps/viewer/src/progressive-granularity.js";
import type { CityBuilding } from "../packages/core/src/model.js";
const building = (units: CityBuilding["units"], location = true): CityBuilding => ({ id: "b", repositoryId: "r", moduleId: "m", districtId: "d", name: "a.ts", path: "a.ts", language: "typescript", metrics: { sloc: 20, decisionLoad: 2, maximumComplexity: 3, executableUnitCount: units?.length ?? 0 }, ...(units === undefined ? {} : { metricMethod: "typescript-compiler-api-v1" as const, units }), ...(location ? { sourceLocation: { startLine: 1, endLine: 20 } } : {}), risk: "low", semanticGroupId: "low", position: { x: 0, y: 0, z: 0 }, size: { x: 1, y: 1, z: 1 } });
describe("progressive granularity", () => {
 it("projects stable source-ranged functions only when drilled into", () => { const detail = projectFineDetail(building([{ name: "z", line: 10, endLine: 12, complexity: 2 }, { name: "a", line: 2, endLine: 5, complexity: 3 }])); expect(detail.nodes.map((node) => node.name)).toEqual(["a", "z"]); expect(detail.nodes[0]).toMatchObject({ id: "b:function:0001", startLine: 2, unitIndex: 1, provenance: "persisted-executable-unit" }); expect(detail.printable.state).toBe("not-printable"); });
 it("bounds large files and says when type facts are not available", () => { const units = Array.from({ length: 300 }, (_, index) => ({ name: `m${index}`, line: index + 1, complexity: 1 })); const detail = projectFineDetail(building(units), 500); expect(detail).toMatchObject({ state: "capped", totalCount: 300, omittedCount: 100, canLoadMore: false }); expect(detail.terminalReason).toContain("capped at 200"); expect(detail.nodes).toHaveLength(200); expect(detail.unavailable[0]).toContain("type/class"); });
 it("does not infer unavailable fine detail", () => { expect(projectFineDetail(building(undefined, false)).state).toBe("unavailable"); });
});
