import { describe, expect, it } from "vitest";
import { ADVANCED_QUERY_PRESETS, ADVANCED_QUERY_RULE_SCHEMA, ADVANCED_QUERY_VERSION, evaluateAdvancedQuery, parseSavedAdvancedQuery, selectQueryRange, serializeSavedAdvancedQuery } from "../apps/viewer/src/advanced-query.js";
import type { CityBuilding, CityModel } from "../packages/core/src/model.js";
import { isAdvancedQueryWorkerMessage, isAdvancedQueryWorkerResponse } from "../apps/viewer/src/advanced-query-protocol.js";

const building = (id: string, maximumComplexity: number, risk = "low"): CityBuilding => ({ id, repositoryId: "r", moduleId: "m", districtId: "d", name: `${id}.ts`, path: `src/${id}.ts`, language: "typescript", metrics: { sloc: maximumComplexity * 10, decisionLoad: maximumComplexity, maximumComplexity, executableUnitCount: 1 }, risk: risk as CityBuilding["risk"], semanticGroupId: "risk", position: { x: 0, y: 0, z: 0 }, size: { x: 1, y: 1, z: 1 } });
const model = (buildings: readonly CityBuilding[]): CityModel => ({ schemaVersion: "1.0", generator: { name: "code-city", version: "test" }, repositories: [], solutions: [], modules: [], semanticGroups: [], districts: [], buildings, dependencies: [{ id: "a-b", repositoryId: "r", sourceId: "a", targetId: "b", kind: "typescript-import", weight: 1 }, { id: "c-b", repositoryId: "r", sourceId: "c", targetId: "b", kind: "typescript-import", weight: 1 }], bounds: { x: 1, y: 1, z: 1 } });
describe("advanced query", () => {
  it("is deterministic, explains metric and dependency matches, and bounds output", () => { const source = model([building("c", 2), building("b", 12), building("a", 15)]); const query = { ...ADVANCED_QUERY_PRESETS["highest-complexity"], all: [{ field: "incomingDependencies" as const, operator: "atLeast" as const, value: 1 }] }; const result = evaluateAdvancedQuery(source, query, new Set(), 1); expect(result).toMatchObject({ state: "results", totalCount: 1, omittedCount: 0 }); expect(result.matches[0]).toMatchObject({ buildingId: "b" }); expect(result.matches[0]?.explanations[0]).toContain("actual 2"); });
  it("reports unavailable history and smell clauses explicitly instead of inventing facts", () => { const result = evaluateAdvancedQuery(model([building("a", 1)]), { version: ADVANCED_QUERY_VERSION, ruleSchema: ADVANCED_QUERY_RULE_SCHEMA, all: [{ field: "changedRecently", operator: "equals", value: "true" }, { field: "smell", operator: "equals", value: "god-class" }] }); expect(result.state).toBe("partial"); expect(result.unavailable.map(({ field }) => field)).toEqual(["changedRecently", "smell"]); });
  it("uses additive and range selection with a stable ordered result set", () => { expect([...selectQueryRange(new Set(["a"]), ["a", "b", "c"], "c", "a", false, true)]).toEqual(["a", "b", "c"]); expect([...selectQueryRange(new Set(["a", "b"]), ["a", "b"], "b", null, true, false)]).toEqual(["a"]); });
  it("round trips versioned saved queries", () => { const serialized = serializeSavedAdvancedQuery({ id: "high", savedAt: "2026-07-31T00:00:00.000Z", query: ADVANCED_QUERY_PRESETS["highest-complexity"] }); expect(parseSavedAdvancedQuery(serialized).query.ruleSchema).toBe(ADVANCED_QUERY_RULE_SCHEMA); });
  it("accepts only exact-shaped worker protocol messages", () => { expect(isAdvancedQueryWorkerMessage({ type: "cancel", jobId: 1 })).toBe(true); expect(isAdvancedQueryWorkerMessage({ type: "cancel", jobId: 1, extra: true })).toBe(false); expect(isAdvancedQueryWorkerResponse({ type: "result", jobId: 1, result: {} })).toBe(true); expect(isAdvancedQueryWorkerResponse({ type: "failure", jobId: 0, message: "no" })).toBe(false); });
  it("keeps a 25k scan bounded to its requested result limit", () => { const source = model(Array.from({ length: 25_000 }, (_, index) => building(`b-${index.toString().padStart(5, "0")}`, index % 9))); const result = evaluateAdvancedQuery(source, { version: ADVANCED_QUERY_VERSION, ruleSchema: ADVANCED_QUERY_RULE_SCHEMA, all: [{ field: "sloc", operator: "atLeast", value: 0 }] }, new Set(), 7); expect(result).toMatchObject({ state: "large", totalCount: 25_000, omittedCount: 24_993 }); expect(result.matches).toHaveLength(7); });
});
