import { promises as dns } from "node:dns";
import http from "node:http";
import https from "node:https";
import net from "node:net";
import tls from "node:tls";
import { Readable } from "node:stream";

export const AI_GUIDANCE_CONFIG_VERSION = 1;
export const AI_GUIDANCE_MAX_SOURCE_BYTES = 128 * 1024;
export const AI_GUIDANCE_MAX_RESPONSE_BYTES = 256 * 1024;
export const AI_GUIDANCE_DEFAULT_TIMEOUT_MS = 20_000;
export const AI_GUIDANCE_MAX_PROVIDERS = 64;
export const AI_GUIDANCE_CONTEXT_VERSION = "codecity.ai-context/1" as const;

const PROVIDER_ID = /^[a-z][a-z0-9-]{0,63}$/u;
const UNSAFE_TEXT = /[\p{Cc}\p{Cf}\p{Cs}]/u;
const SAFE_AUTHORIZATION_HEADERS = new Set(["authorization", "api-key", "x-api-key"]);

export interface AiGuidanceProviderConfiguration { readonly id: string; readonly label: string; readonly endpoint: string; readonly authorization?: { readonly header: string; readonly value: string }; }
export interface AiGuidanceConfiguration { readonly version: typeof AI_GUIDANCE_CONFIG_VERSION; readonly enabled: boolean; readonly providers: readonly AiGuidanceProviderConfiguration[]; readonly timeoutMs?: number; readonly maximumSourceBytes?: number; }
export type AiGuidanceContextDescriptor =
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "file"; buildingId: string }>
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "type" | "callable"; buildingId: string; stableId: string }>
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "dependency"; buildingId: string; dependencyId: string }>
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "smell"; buildingId: string; findingId: string; ruleId: string }>;
export interface AiGuidanceSourceRange { readonly startLine: number; readonly endLine: number; readonly startColumn?: number; readonly endColumn?: number; }
export type AiGuidanceResolvedContext =
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "file"; buildingId: string; label: string; range: AiGuidanceSourceRange }>
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "type" | "callable"; buildingId: string; stableId: string; name: string; constructKind: string; label: string; range: AiGuidanceSourceRange }>
  | Readonly<{ version: typeof AI_GUIDANCE_CONTEXT_VERSION; kind: "smell"; buildingId: string; findingId: string; ruleId: string; label: string; range: AiGuidanceSourceRange; evidence: Readonly<Record<string, unknown>> }>;
export interface AiGuidanceSource { readonly jobId: string; readonly buildingId: string; readonly path: string; readonly language: string; readonly text: string; readonly location: AiGuidanceSourceRange; }
export interface AiGuidanceMetrics { readonly sloc: number; readonly maximumComplexity: number; readonly decisionLoad: number; }
export interface AiGuidanceSelection { readonly source: AiGuidanceSource; readonly metrics: AiGuidanceMetrics; readonly context: AiGuidanceResolvedContext; readonly contextDigest: string; readonly findingDigest?: string; }
export interface AiGuidanceProviderPayload { readonly version: 1; readonly task: "source-guidance"; readonly providerId: string; readonly context: AiGuidanceResolvedContext; readonly contextDigest: string; readonly findingDigest?: string; readonly source: { readonly path: string; readonly language: string; readonly text: string; readonly lines: AiGuidanceSource["location"] }; readonly findings: AiGuidanceMetrics; }
export type AiGuidancePreview =
  | Readonly<{ enabled: false; availability: "disabled"; transmission?: undefined; limits: { readonly timeoutMs: number; readonly maximumSourceBytes: number }; privacy: "no-prompt-storage" }>
  | Readonly<{ enabled: true; availability: "unavailable"; provider: { readonly id: string; readonly label: string }; context: AiGuidanceContextDescriptor; reason: string; transmission?: undefined; limits: { readonly timeoutMs: number; readonly maximumSourceBytes: number }; privacy: "no-prompt-storage" }>
  | Readonly<{ enabled: true; availability: "available"; provider: { readonly id: string; readonly label: string }; transmission: AiGuidanceProviderPayload; limits: { readonly timeoutMs: number; readonly maximumSourceBytes: number }; privacy: "no-prompt-storage" }>;
export interface AiGuidanceSuggestion { readonly title: string; readonly detail: string; readonly citation: { readonly path: string; readonly startLine: number; readonly endLine: number }; }
export interface AiGuidanceResult { readonly provider: { readonly id: string; readonly label: string }; readonly context: AiGuidanceResolvedContext; readonly contextDigest: string; readonly findingDigest?: string; readonly suggestions: readonly AiGuidanceSuggestion[]; }
export type AiGuidanceFetch = (input: string | URL, init: RequestInit) => Promise<Response>;
export type AiGuidanceAuditEvent = Readonly<{ providerId: string; buildingId: string; outcome: "completed" | "cancelled" | "failed"; sourceBytes: number; durationMs: number }>;
export type AiGuidanceResolve = (hostname: string) => Promise<readonly string[]>;
export interface AiGuidanceAdapterOptions { readonly fetch?: AiGuidanceFetch; readonly resolve?: AiGuidanceResolve; readonly audit?: (event: AiGuidanceAuditEvent) => void; }

function checkedText(value: string, label: string, maximum: number): void { if (value.length === 0 || value.length > maximum || UNSAFE_TEXT.test(value)) throw new Error(`${label} is invalid.`); }
function ipv4Public(value: string): boolean { const octets = value.split(".").map(Number); if (octets.length !== 4 || octets.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return false; const [a = -1, b = -1] = octets; return !(a === 0 || a === 10 || a === 127 || a >= 224 || (a === 100 && b >= 64 && b <= 127) || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && (b === 0 || b === 168)) || (a === 198 && (b === 18 || b === 19 || b === 51)) || (a === 203 && b === 0)); }
function ipv6Groups(value: string): readonly number[] | undefined { let normalized = value.toLowerCase(); const dotted = /(?:^|:)(\d+\.\d+\.\d+\.\d+)$/u.exec(normalized); if (dotted !== null) { const parts = dotted[1]!.split(".").map(Number); if (parts.length !== 4 || parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return undefined; normalized = `${normalized.slice(0, normalized.length - dotted[1]!.length)}${((parts[0]! << 8) | parts[1]!).toString(16)}:${((parts[2]! << 8) | parts[3]!).toString(16)}`; } const halves = normalized.split("::"); if (halves.length > 2) return undefined; const left = halves[0] === "" ? [] : halves[0]!.split(":"); const right = halves.length === 1 || halves[1] === "" ? [] : halves[1]!.split(":"); if (left.length + right.length > 8 || (halves.length === 1 && left.length !== 8)) return undefined; const parts = [...left, ...Array(Math.max(0, 8 - left.length - right.length)).fill("0"), ...right]; if (parts.length !== 8 || parts.some((part) => !/^[0-9a-f]{1,4}$/u.test(part))) return undefined; return parts.map((part) => Number.parseInt(part, 16)); }
function ipv6Public(value: string): boolean { const groups = ipv6Groups(value); if (groups === undefined) return false; const first = groups[0]!; const allZero = groups.every((group) => group === 0); const loopback = groups.slice(0, 7).every((group) => group === 0) && groups[7] === 1; if (allZero || loopback || (first & 0xfe00) === 0xfc00 || (first & 0xffc0) === 0xfe80 || (first & 0xf000) === 0xf000) return false; const compatible = groups.slice(0, 6).every((group) => group === 0); const mapped = groups.slice(0, 5).every((group) => group === 0) && groups[5] === 0xffff; if (compatible || mapped) return ipv4Public(`${groups[6]! >> 8}.${groups[6]! & 255}.${groups[7]! >> 8}.${groups[7]! & 255}`); return true; }
// Kept in step with the IANA special-purpose registries. The IPv6 policy is
// deliberately conservative: only 2000::/3 global unicast is admitted, with
// transition, translation, documentation, and protocol-assignment ranges
// removed. This avoids interpreting an embedded private IPv4 address as public.
const SPECIAL_IPV4_ADDRESSES = new net.BlockList();
const SPECIAL_IPV6_ADDRESSES = new net.BlockList();
for (const [address, prefix] of [
  ["0.0.0.0", 8], ["10.0.0.0", 8], ["100.64.0.0", 10],
  ["127.0.0.0", 8], ["169.254.0.0", 16], ["172.16.0.0", 12],
  ["192.0.0.0", 24], ["192.0.2.0", 24], ["192.88.99.0", 24],
  ["192.168.0.0", 16], ["198.18.0.0", 15], ["198.51.100.0", 24],
  ["203.0.113.0", 24], ["224.0.0.0", 4], ["240.0.0.0", 4],
] as const) SPECIAL_IPV4_ADDRESSES.addSubnet(address, prefix, "ipv4");
for (const [address, prefix] of [
  ["::", 96], ["::ffff:0:0", 96], ["64:ff9b::", 96],
  ["64:ff9b:1::", 48], ["100::", 64], ["2001::", 23],
  ["2001:db8::", 32], ["2002::", 16], ["3fff::", 20],
  ["fc00::", 7], ["fe80::", 10], ["fec0::", 10], ["ff00::", 8],
] as const) SPECIAL_IPV6_ADDRESSES.addSubnet(address, prefix, "ipv6");
function publicAddress(value: string): boolean {
  const family = net.isIP(value);
  if (family === 4) return ipv4Public(value) && !SPECIAL_IPV4_ADDRESSES.check(value, "ipv4");
  if (family !== 6 || !ipv6Public(value) || SPECIAL_IPV6_ADDRESSES.check(value, "ipv6")) return false;
  const groups = ipv6Groups(value);
  return groups !== undefined && (groups[0]! & 0xe000) === 0x2000;
}
function loopbackAddress(value: string): boolean { const normalized = value.toLowerCase(); return normalized === "::1" || normalized.startsWith("127."); }
function isLocalHost(hostname: string): boolean { return hostname.toLowerCase() === "localhost"; }
function endpointHostname(url: URL): string { return url.hostname.startsWith("[") && url.hostname.endsWith("]") ? url.hostname.slice(1, -1) : url.hostname; }

function safeEndpoint(value: string): URL { let endpoint: URL; try { endpoint = new URL(value); } catch { throw new Error("AI provider endpoint must be an absolute URL."); } if (endpoint.username !== "" || endpoint.password !== "" || endpoint.search !== "" || endpoint.hash !== "" || !["http:", "https:"].includes(endpoint.protocol)) throw new Error("AI provider endpoint must be a credential-free HTTP(S) URL without query or fragment."); const host = endpointHostname(endpoint).toLowerCase(); const family = net.isIP(host); const local = isLocalHost(host) || (family !== 0 && loopbackAddress(host)); if (endpoint.protocol === "http:" && !local) throw new Error("Only literal localhost/loopback AI endpoints may use HTTP."); if (family !== 0 && !local && !publicAddress(host)) throw new Error("AI provider endpoint must not use a private, link-local, loopback, or special address."); return endpoint; }

function normalized(config: AiGuidanceConfiguration | undefined): Required<Pick<AiGuidanceConfiguration, "enabled">> & { readonly providers: readonly (AiGuidanceProviderConfiguration & { readonly url: URL })[]; readonly timeoutMs: number; readonly maximumSourceBytes: number } { if (config === undefined) return Object.freeze({ enabled: false, providers: Object.freeze([]), timeoutMs: AI_GUIDANCE_DEFAULT_TIMEOUT_MS, maximumSourceBytes: AI_GUIDANCE_MAX_SOURCE_BYTES }); if (config.version !== AI_GUIDANCE_CONFIG_VERSION || typeof config.enabled !== "boolean" || !Array.isArray(config.providers)) throw new Error("AI guidance configuration must use version 1."); if (config.providers.length > AI_GUIDANCE_MAX_PROVIDERS) throw new Error(`AI guidance supports at most ${AI_GUIDANCE_MAX_PROVIDERS} providers.`); const timeoutMs = config.timeoutMs ?? AI_GUIDANCE_DEFAULT_TIMEOUT_MS; const maximumSourceBytes = config.maximumSourceBytes ?? AI_GUIDANCE_MAX_SOURCE_BYTES; if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 1_000 || timeoutMs > 60_000 || !Number.isSafeInteger(maximumSourceBytes) || maximumSourceBytes < 1 || maximumSourceBytes > AI_GUIDANCE_MAX_SOURCE_BYTES) throw new Error("AI guidance limits are invalid."); const ids = new Set<string>(); const providers = config.providers.map((provider) => { if (provider === null || typeof provider !== "object" || !PROVIDER_ID.test(provider.id) || ids.has(provider.id)) throw new Error("AI provider ID is invalid or duplicated."); ids.add(provider.id); checkedText(provider.label, "AI provider label", 120); const url = safeEndpoint(provider.endpoint); if (provider.authorization !== undefined) { const header = provider.authorization.header.toLowerCase(); if (!SAFE_AUTHORIZATION_HEADERS.has(header) || provider.authorization.value.length === 0 || provider.authorization.value.length > 8_192 || /[\r\n]/u.test(provider.authorization.value)) throw new Error("AI provider authorization is invalid."); return Object.freeze({ ...provider, authorization: Object.freeze({ header, value: provider.authorization.value }), url }); } return Object.freeze({ ...provider, url }); }); if (config.enabled && providers.length === 0) throw new Error("Enabled AI guidance requires at least one provider."); return Object.freeze({ enabled: config.enabled, providers: Object.freeze(providers), timeoutMs, maximumSourceBytes }); }
function publicProvider(provider: AiGuidanceProviderConfiguration): { readonly id: string; readonly label: string } { return Object.freeze({ id: provider.id, label: provider.label }); }
function providerPayload(selection: AiGuidanceSelection, providerId: string): AiGuidanceProviderPayload { return Object.freeze({ version: 1, task: "source-guidance", providerId, context: selection.context, contextDigest: selection.contextDigest, ...(selection.findingDigest === undefined ? {} : { findingDigest: selection.findingDigest }), source: Object.freeze({ path: selection.source.path, language: selection.source.language, text: selection.source.text, lines: selection.source.location }), findings: Object.freeze({ ...selection.metrics }) }); }
function validSource(source: AiGuidanceSource): number { if (!PROVIDER_ID.test(source.buildingId.split(":")[0] ?? "") || source.path.length === 0 || source.path.length > 4_096 || UNSAFE_TEXT.test(source.path) || !Number.isSafeInteger(source.location.startLine) || !Number.isSafeInteger(source.location.endLine) || source.location.startLine < 1 || source.location.endLine < source.location.startLine) throw new Error("Selected source is outside the AI guidance limits."); return new TextEncoder().encode(source.text).byteLength; }
function validMetrics(metrics: AiGuidanceMetrics): void { for (const value of [metrics.sloc, metrics.maximumComplexity, metrics.decisionLoad]) if (!Number.isSafeInteger(value) || value < 0) throw new Error("AI guidance metrics are invalid."); }
function validDigest(value: string, label: string): void { if (!/^[0-9a-f]{64}$/u.test(value)) throw new Error(`${label} is invalid.`); }
function validSelection(selection: AiGuidanceSelection): number {
  const sourceBytes = validSource(selection.source);
  validMetrics(selection.metrics);
  validDigest(selection.contextDigest, "AI context digest");
  if (selection.findingDigest !== undefined) validDigest(selection.findingDigest, "AI finding digest");
  if ((selection.context.kind === "smell") !== (selection.findingDigest !== undefined)) throw new Error("AI finding digest does not match the selected context.");
  if (selection.context.buildingId !== selection.source.buildingId || selection.context.range.startLine !== selection.source.location.startLine || selection.context.range.endLine !== selection.source.location.endLine) throw new Error("AI context does not match the selected source.");
  return sourceBytes;
}
function contextDescriptor(context: AiGuidanceResolvedContext): AiGuidanceContextDescriptor {
  if (context.kind === "file") return Object.freeze({ version: context.version, kind: context.kind, buildingId: context.buildingId });
  if ("stableId" in context) return Object.freeze({ version: context.version, kind: context.kind, buildingId: context.buildingId, stableId: context.stableId });
  return Object.freeze({ version: context.version, kind: context.kind, buildingId: context.buildingId, findingId: context.findingId, ruleId: context.ruleId });
}
function responseSuggestions(value: unknown, selection: AiGuidanceSelection, providerId: string): readonly AiGuidanceSuggestion[] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("AI provider returned an invalid response.");
  const object = value as Record<string, unknown>;
  const expectedKeys = selection.findingDigest === undefined ? ["contextDigest", "providerId", "suggestions"] : ["contextDigest", "findingDigest", "providerId", "suggestions"];
  if (Object.keys(object).length !== expectedKeys.length || expectedKeys.some((key) => !(key in object)) || object["providerId"] !== providerId || object["contextDigest"] !== selection.contextDigest || object["findingDigest"] !== selection.findingDigest || !Array.isArray(object["suggestions"])) throw new Error("AI provider returned a stale, mismatched, or invalid response.");
  const suggestions = object["suggestions"];
  if (suggestions.length > 20) throw new Error("AI provider returned too many suggestions.");
  return Object.freeze(suggestions.map((suggestion) => {
    if (typeof suggestion !== "object" || suggestion === null || Array.isArray(suggestion) || Object.keys(suggestion).some((key) => key !== "title" && key !== "detail")) throw new Error("AI provider returned an invalid suggestion.");
    const item = suggestion as Record<string, unknown>;
    if (typeof item["title"] !== "string" || typeof item["detail"] !== "string") throw new Error("AI provider returned an invalid suggestion.");
    checkedText(item["title"], "AI suggestion title", 500); checkedText(item["detail"], "AI suggestion detail", 8_000);
    return Object.freeze({ title: item["title"], detail: item["detail"], citation: Object.freeze({ path: selection.source.path, startLine: selection.source.location.startLine, endLine: selection.source.location.endLine }) });
  }));
}
async function defaultResolve(hostname: string): Promise<readonly string[]> { return (await dns.lookup(hostname, { all: true, verbatim: true })).map(({ address }) => address); }
function hostHeader(url: URL): string { const port = url.port === "" || (url.protocol === "https:" && url.port === "443") || (url.protocol === "http:" && url.port === "80") ? "" : `:${url.port}`; return `${url.hostname}${port}`; }
function pinnedFetch(url: URL, address: string, body: string, headers: Record<string, string>, signal: AbortSignal): Promise<Response> { const client = url.protocol === "https:" ? https : http; const certificateHost = endpointHostname(url); return new Promise((resolve, reject) => { if (signal.aborted) { reject(signal.reason ?? new Error("AI guidance request was cancelled.")); return; } const request = client.request({ protocol: url.protocol, hostname: address, port: url.port === "" ? undefined : Number(url.port), path: url.pathname, method: "POST", headers: { ...headers, host: hostHeader(url) }, agent: false, ...(url.protocol === "https:" ? { servername: certificateHost, checkServerIdentity: (_name: string, certificate: tls.PeerCertificate) => tls.checkServerIdentity(certificateHost, certificate) } : {}) }, (response) => { const outputHeaders = new Headers(); for (const [name, value] of Object.entries(response.headers)) for (const item of Array.isArray(value) ? value : [value]) if (item !== undefined) outputHeaders.append(name, String(item)); resolve(new Response(Readable.toWeb(response) as ReadableStream, { status: response.statusCode ?? 502, headers: outputHeaders })); }); const abort = (): void => { request.destroy(signal.reason instanceof Error ? signal.reason : new Error("AI guidance request was cancelled.")); }; signal.addEventListener("abort", abort, { once: true }); request.once("error", (error) => { signal.removeEventListener("abort", abort); reject(error); }); request.once("close", () => signal.removeEventListener("abort", abort)); request.end(body); }); }
async function boundedResponseText(response: Response): Promise<string> { const declared = response.headers.get("content-length"); if (declared !== null && (!/^\d+$/u.test(declared) || Number(declared) > AI_GUIDANCE_MAX_RESPONSE_BYTES)) { await response.body?.cancel(); throw new Error("AI provider response exceeded the size limit."); } if (response.body === null) return ""; const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let size = 0; try { while (true) { const { done, value } = await reader.read(); if (done) break; size += value.byteLength; if (size > AI_GUIDANCE_MAX_RESPONSE_BYTES) { await reader.cancel(); throw new Error("AI provider response exceeded the size limit."); } chunks.push(value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } try { return new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw new Error("AI provider returned invalid UTF-8."); } }
async function cancelResponseBody(response: Response): Promise<void> { try { await response.body?.cancel(); } catch { /* Transport cleanup must not replace the provider failure. */ } }
function jsonResponse(response: Response): boolean { const contentType = response.headers.get("content-type"); return contentType !== null && /^application\/json(?:\s*;\s*charset=utf-8)?$/iu.test(contentType); }
function abortable<T>(operation: Promise<T>, signal: AbortSignal): Promise<T> { if (signal.aborted) return Promise.reject(signal.reason ?? new Error("AI guidance request was cancelled.")); return new Promise<T>((resolve, reject) => { const abort = () => reject(signal.reason ?? new Error("AI guidance request was cancelled.")); signal.addEventListener("abort", abort, { once: true }); operation.then((value) => { signal.removeEventListener("abort", abort); resolve(value); }, (error) => { signal.removeEventListener("abort", abort); reject(error); }); }); }

export class AiGuidanceAdapter {
  readonly #config: ReturnType<typeof normalized>; readonly #fetch: AiGuidanceFetch | undefined; readonly #resolve: AiGuidanceResolve; readonly #audit: AiGuidanceAdapterOptions["audit"];
  public constructor(config: AiGuidanceConfiguration | undefined, options: AiGuidanceAdapterOptions = {}) { this.#config = normalized(config); this.#fetch = options.fetch; this.#resolve = options.resolve ?? defaultResolve; this.#audit = options.audit; }
  public get enabled(): boolean { return this.#config.enabled; }
  public providers(): readonly { readonly id: string; readonly label: string }[] { return Object.freeze(this.#config.enabled ? this.#config.providers.map(publicProvider) : []); }
  public disabledPreview(): AiGuidancePreview { return Object.freeze({ enabled: false, availability: "disabled", limits: Object.freeze({ timeoutMs: this.#config.timeoutMs, maximumSourceBytes: this.#config.maximumSourceBytes }), privacy: "no-prompt-storage" }); }
  public unavailablePreview(context: AiGuidanceContextDescriptor, reason: string, providerId: string): AiGuidancePreview { const provider = this.#config.providers.find((candidate) => candidate.id === providerId); if (!this.#config.enabled || provider === undefined) return this.disabledPreview(); checkedText(reason, "AI context unavailability reason", 1_000); return Object.freeze({ enabled: true, availability: "unavailable", provider: publicProvider(provider), context, reason, limits: Object.freeze({ timeoutMs: this.#config.timeoutMs, maximumSourceBytes: this.#config.maximumSourceBytes }), privacy: "no-prompt-storage" }); }
  public preview(selection: AiGuidanceSelection, providerId: string): AiGuidancePreview { const provider = this.#config.providers.find((candidate) => candidate.id === providerId); if (!this.#config.enabled || provider === undefined) return this.disabledPreview(); const sourceBytes = validSelection(selection); if (sourceBytes > this.#config.maximumSourceBytes) return this.unavailablePreview(contextDescriptor(selection.context), `The exact selected source is ${sourceBytes} UTF-8 bytes, exceeding the configured maximum of ${this.#config.maximumSourceBytes} bytes. It was not truncated and no source was sent to an AI provider.`, provider.id); return Object.freeze({ enabled: true, availability: "available", provider: publicProvider(provider), transmission: providerPayload(selection, provider.id), limits: Object.freeze({ timeoutMs: this.#config.timeoutMs, maximumSourceBytes: this.#config.maximumSourceBytes }), privacy: "no-prompt-storage" }); }
  #emitAudit(event: AiGuidanceAuditEvent): void { try { this.#audit?.(Object.freeze(event)); } catch { /* Audit sinks are best-effort and isolated. */ } }
  async #addresses(url: URL, signal: AbortSignal): Promise<readonly string[]> { const hostname = endpointHostname(url); if (isLocalHost(hostname)) return ["127.0.0.1"]; if (net.isIP(hostname) !== 0) return [hostname]; const addresses = await abortable(Promise.resolve(this.#resolve(hostname)), signal); if (addresses.length === 0 || addresses.some((address) => !publicAddress(address))) throw new Error("AI provider hostname resolved to an unsafe address."); return addresses; }
  public async request(selection: AiGuidanceSelection, providerId: string, signal?: AbortSignal): Promise<AiGuidanceResult> { const preview = this.preview(selection, providerId); const provider = this.#config.providers.find((candidate) => candidate.id === providerId); if (!preview.enabled || provider === undefined) throw new Error("AI guidance is disabled by the administrator."); if (preview.availability !== "available") throw new Error(preview.reason); const started = Date.now(); const bytes = new TextEncoder().encode(selection.source.text).byteLength; if (signal?.aborted) { this.#emitAudit({ providerId: provider.id, buildingId: selection.source.buildingId, outcome: "cancelled", sourceBytes: bytes, durationMs: 0 }); throw new Error("AI guidance request was cancelled or timed out."); } const controller = new AbortController(); const timer = setTimeout(() => controller.abort(new Error("AI guidance request timed out.")), this.#config.timeoutMs); const forwardAbort = () => controller.abort(signal?.reason); signal?.addEventListener("abort", forwardAbort, { once: true }); let outcome: AiGuidanceAuditEvent["outcome"] = "failed"; try { const headers: Record<string, string> = { "content-type": "application/json", accept: "application/json" }; if (provider.authorization !== undefined) headers[provider.authorization.header] = provider.authorization.value; const body = JSON.stringify(preview.transmission); const addresses = await this.#addresses(provider.url, controller.signal); if (controller.signal.aborted) throw controller.signal.reason ?? new Error("AI guidance request was cancelled."); const response = this.#fetch === undefined ? await pinnedFetch(provider.url, addresses[0]!, body, headers, controller.signal) : await this.#fetch(provider.url, { method: "POST", headers, redirect: "error", signal: controller.signal, body }); if (!response.ok) { await cancelResponseBody(response); throw new Error("Configured AI provider did not complete the request."); } if (!jsonResponse(response)) { await cancelResponseBody(response); throw new Error("AI provider returned an invalid content type."); } const text = await boundedResponseText(response); const suggestions = responseSuggestions(JSON.parse(text), selection, provider.id); outcome = "completed"; return Object.freeze({ provider: publicProvider(provider), context: selection.context, contextDigest: selection.contextDigest, ...(selection.findingDigest === undefined ? {} : { findingDigest: selection.findingDigest }), suggestions }); } catch (error) { if (controller.signal.aborted) { outcome = "cancelled"; throw new Error("AI guidance request was cancelled or timed out."); } throw error; } finally { clearTimeout(timer); signal?.removeEventListener("abort", forwardAbort); this.#emitAudit({ providerId: provider.id, buildingId: selection.source.buildingId, outcome, sourceBytes: bytes, durationMs: Date.now() - started }); } }
}
