import type { CityModel, DesignSmellConfiguration, DesignSmellEvaluation, DesignSmellSuppression } from "../../../packages/core/src/index.js";

export interface DesignSmellEvaluateRequest { readonly type: "evaluate"; readonly jobId: number; readonly model: CityModel; readonly configuration: DesignSmellConfiguration; readonly suppressions: readonly DesignSmellSuppression[]; }
export type DesignSmellWorkerResponse = { readonly type: "result"; readonly jobId: number; readonly evaluation: DesignSmellEvaluation } | { readonly type: "failure"; readonly jobId: number; readonly message: string };
const record = (value: unknown): Record<string, unknown> | undefined => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
const exact = (value: Record<string, unknown>, keys: readonly string[]): boolean => Object.keys(value).sort().join("\u0000") === [...keys].sort().join("\u0000");
const job = (value: unknown): value is number => Number.isSafeInteger(value) && Number(value) > 0;
export function isDesignSmellEvaluateRequest(value: unknown): value is DesignSmellEvaluateRequest { const item = record(value); return !!item && exact(item, ["type", "jobId", "model", "configuration", "suppressions"]) && item.type === "evaluate" && job(item.jobId) && !!record(item.model) && !!record(item.configuration) && Array.isArray(item.suppressions); }
export function isDesignSmellWorkerResponse(value: unknown): value is DesignSmellWorkerResponse { const item = record(value); return !!item && job(item.jobId) && ((item.type === "result" && exact(item, ["type", "jobId", "evaluation"]) && !!record(item.evaluation)) || (item.type === "failure" && exact(item, ["type", "jobId", "message"]) && typeof item.message === "string" && item.message.length > 0 && item.message.length <= 512)); }
export function designSmellFailureMessage(error: unknown): string { return (error instanceof Error && error.message.trim() ? error.message.trim() : "Design-smell evaluation failed.").slice(0, 512); }
